plugins {
    alias(libs.plugins.loom)
}

loom {
    log4jConfigs.from(file('../log4j.xml'))
    runs {
        remove server
    }
}

dependencies {
    shadow project(':common')

    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment variantOf(libs.parchment) {
            artifactType('zip')
        }
    }

    modImplementation libs.fabricLoader

    modRuntimeOnly libs.fabricApi
    include libs.fabricApi

    modRuntimeOnly libs.architecturyApiFabric
    include libs.architecturyApiFabric

    modImplementation libs.clothConfigFabric
    include libs.clothConfigFabric

    modImplementation libs.modMenu
}

remapJar {
    dependsOn shadowJar
    inputFile.set shadowJar.archiveFile
}
