version: 2

multi-ecosystem-groups:
  dependencies:
    assignees:
      - BrailleBennett
    schedule:
      interval: weekly
      day: sunday

updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    assignees:
      - BrailleBennett
      - TheSuperGamer20578
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: dependencies

  - package-ecosystem: nix
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: dependencies

  - package-ecosystem: gradle
    directory: "/"
    patterns: [ "*" ]
    ignore:
      - dependency-name: "maven.modrinth:jade"
      - dependency-name: "net.neoforged.fancymodloader:loader"
        versions: [ ">= 47.0, < 48.0" ]
    multi-ecosystem-group: dependencies
