version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
          
  # All Gradle dependencies grouped together
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
        
  - package-ecosystem: "gradle"
    directory: "/common"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
        
  - package-ecosystem: "gradle"
    directory: "/fabric"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
        
  - package-ecosystem: "gradle"
    directory: "/neoforge"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch