pluginManagement {
    repositories {
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Neoforged'
            url = 'https://maven.neoforged.net/releases/'
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'com.gradle.develocity' version '4.2.1'
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev'
        }
        mavenCentral()
        maven{
            name = 'Cloth Config'
            url = 'https://maven.shedaniel.me/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Mod Menu'
            url = 'https://maven.terraformersmc.com/'
        }
        maven {
            name = 'Neoforged'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Modrinth'
                    url = 'https://api.modrinth.com/maven'
                }
            }
            filter {
                includeGroup 'maven.modrinth'
            }
        }
    }
}

include("common")
include("fabric")
include("neoforge")

rootProject.name = "minecraft_access"
