import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = 'https://maven.fabricmc.net/'
                }
            }
            filter {
                includeGroupAndSubgroups 'net.fabricmc'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Neoforged'
                    url = 'https://maven.neoforged.net/releases/'
                }
            }
            filter {
                includeGroupAndSubgroups 'net.neoforged'
                includeGroup 'de.oceanlabs.mcp'
            }
        }

        gradlePluginPortal()
    }
}

plugins {
    id 'com.gradle.develocity' version '4.5.0'
    id 'net.fabricmc.fabric-loom-repositories' version '1.17.17'
    id 'net.neoforged.moddev.repositories' version '2.0.142'
}

develocity {
    buildScan {
        publishing.onlyIf { System.getenv('CI') == 'true' }
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS

    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Balm'
                    url = 'https://maven.twelveiterations.com/repository/maven-public/'
                }
            }
            filter {
                includeGroup 'net.blay09.mods'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Cloth Config'
                    url = 'https://maven.shedaniel.me/'
                }
            }
            filter {
                includeGroup 'me.shedaniel.cloth'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = 'https://maven.fabricmc.net/'
                }
            }
            filter {
                includeGroup 'net.fabricmc'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Mod Menu'
                    url = 'https://maven.terraformersmc.com/'
                }
            }
            filter {
                includeGroup 'com.terraformersmc'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Neoforged Releases'
                    url = 'https://maven.neoforged.net/releases/'
                }
            }
            filter {
                includeGroupAndSubgroups 'net.minecraftforge'
                includeGroupAndSubgroups 'cpw.mods'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Tolk'
                    url = 'https://repo.granny.dev/releases/'
                }
            }
            filter {
                includeGroup 'com.davykager.tolk'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Modrinth'
                    url = 'https://api.modrinth.com/maven'
                }
            }
            filter {
                includeGroup 'maven.modrinth'
            }
        }

        mavenCentral()
    }
}

rootProject.name = 'minecraft_access'
include 'fabric'
include 'neoforge'
