modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/minecraft-access/minecraft-access/issues/"
license = "GPL-3.0-only"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib, TheSuperGamer20578, BrailleBennett, and contributors"
description = '''
A mod that helps visually impaired players play Minecraft.
'''
logoFile = "logo-mc-access.png"
modUrl = "https://modrinth.com/mod/jGzXyfdm/"
displayURL = "https://mcaccess.org/"

[[dependencies.minecraft_access]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"

[[dependencies.minecraft_access]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"

[[dependencies.minecraft_access]]
modId = "balm"
type = "required"
versionRange = "[${balm_version},)"
ordering = "BEFORE"
side = "CLIENT"

[[dependencies.minecraft_access]]
modId = "jade"
type = "optional"
reason = "Jade can be used to integrate with the built in narrator of the mod by improving support with other mods and providing more information about things you look at"
versionRange = "[${jade_neoforge_version},)"

[mc-publish]
dependencies = [
    "balm@${balm_version}(embedded){modrinth:MBAkmtvl}{curseforge:531761}",
    "jade@${jade_neoforge_version}(optional){modrinth:nvQzSEkH}{curseforge:324717}",
]

[[mixins]]
config = "minecraft_access.mixins.json"

[[mixins]]
config = "minecraft_access-compat.mixins.json"
