# To manually find version numbers, use
# https://linkie.shedaniel.dev/dependencies
# https://parchmentmc.org/docs/getting-started for version table

[versions]
architecturyApi = "18.0.6"
clothConfig = "20.0.149"
jmh = "1.37"
junit = "6.0.0"
mockito = "5.20.0"

[libraries]
architecturyApi = { module = "dev.architectury:architectury", version.ref = "architecturyApi" }
architecturyApiFabric = { module = "dev.architectury:architectury-fabric", version.ref = "architecturyApi" }
architecturyApiNeoForge = { module = "dev.architectury:architectury-neoforge", version.ref = "architecturyApi" }
clothConfig = { module = "me.shedaniel.cloth:cloth-config", version.ref = "clothConfig" }
clothConfigFabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
clothConfigNeoForge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothConfig" }
fabricApi = "net.fabricmc.fabric-api:fabric-api:0.136.1+"
fabricLoader = "net.fabricmc:fabric-loader:0.17.3"
jadeFabric = "maven.modrinth:jade:20.0.5+fabric"
jadeNeoForge = "maven.modrinth:jade:20.0.5+neoforge"
lombok = "org.projectlombok:lombok:1.18.42"
minecraft = "com.mojang:minecraft:1.21.10"
modMenu = "com.terraformersmc:modmenu:16.0.0-rc.1"
neoForge = "net.neoforged:neoforge:21.10.38-beta"
parchment = "org.parchmentmc.data:parchment-1.21.10:2025.10.12"

assertjCore = "org.assertj:assertj-core:3.27.6"
jmhCore = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmhGeneratorAnnprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoJunitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

checkstyle = "com.puppycrawl.tools:checkstyle:12.1.0"

[plugins]
architecturyLoom = { id = "dev.architectury.loom", version = "1.11.454" }
architecturyPlugin = { id = "architectury-plugin", version = "3.4.162" }
gitVersion = { id = "com.palantir.git-version", version = "4.1.0" }
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
