# To manually find version numbers, use
# https://linkie.shedaniel.dev/dependencies
# https://parchmentmc.org/docs/getting-started for version table

[versions]
architecturyApi = "17.0.6"
clothConfig = "19.0.146"
jmh = "1.37"
junitJupiter = "5.13.1"
mockito = "5.18.0"

[libraries]
architecturyApi = { module = "dev.architectury:architectury", version.ref = "architecturyApi" }
architecturyApiFabric = { module = "dev.architectury:architectury-fabric", version.ref = "architecturyApi" }
architecturyApiNeoForge = { module = "dev.architectury:architectury-neoforge", version.ref = "architecturyApi" }
clothConfig = { module = "me.shedaniel.cloth:cloth-config", version.ref = "clothConfig" }
clothConfigFabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
clothConfigNeoForge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothConfig" }
fabricApi = "net.fabricmc.fabric-api:fabric-api:0.127.1+1.21.6"
fabricLoader = "net.fabricmc:fabric-loader:0.16.14"
jadeFabric = "maven.modrinth:jade:19.0.3+fabric"
jadeNeoForge = "maven.modrinth:jade:19.0.3+neoforge"
minecraft = "com.mojang:minecraft:1.21.6"
modMenu = "com.terraformersmc:modmenu:15.0.0-beta.2"
neoForge = "net.neoforged:neoforge:21.6.4-beta"
parchment = "org.parchmentmc.data:parchment-1.21.5:2025.06.15"

assertjCore = "org.assertj:assertj-core:3.27.3"
jmhCore = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmhGeneratorAnnprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
junitPlatformLauncher = "org.junit.platform:junit-platform-launcher:1.13.1"
lombok = "org.projectlombok:lombok:1.18.38"
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoJunitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
architecturyLoom = { id = "dev.architectury.loom", version = "1.10.431" }
architecturyPlugin = { id = "architectury-plugin", version = "3.4.161" }
gitVersion = { id = "com.palantir.git-version", version = "3.3.0" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
