package org.mcaccess.minecraftaccess.utils;

import com.mojang.blaze3d.platform.InputConstants;
import net.minecraft.client.KeyMapping;

/**
 * Initializes all the keybindings used by the mod.
 */
public enum KeyBindingsHandler {
    NARRATE_PLAYER_STATUS_KEY(
            "minecraft_access.keys.other.player_status_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_R,
            "minecraft_access.keys.other.group_name"
    ),
    LOCKING_HANDLER_KEY(
            "minecraft_access.keys.other.locking_handler_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_Y,
            "minecraft_access.keys.other.group_name"
    ),
    POSITION_NARRATION_KEY(
            "minecraft_access.keys.other.player_position_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_V,
            "minecraft_access.keys.other.group_name"
    ),
    ACCESS_MENU_KEY(
            "minecraft_access.keys.other.access_menu_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_F4,
            "minecraft_access.keys.other.group_name"
    ),
    NARRATE_TARGET(
            "minecraft_access.access_menu.gui.button.block_and_fluid_target_info",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_B,
            "minecraft_access.keys.other.group_name"
    ),
    TARGET_POSITION(
            "minecraft_access.access_menu.gui.button.block_and_fluid_target_position",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    LIGHT_LEVEL(
            "minecraft_access.access_menu.gui.button.light_level",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    CLOSEST_WATER_SOURCE(
            "minecraft_access.access_menu.gui.button.find_water",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    CLOSEST_LAVA_SOURCE(
            "minecraft_access.access_menu.gui.button.find_lava",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    CURRENT_BIOME(
            "minecraft_access.access_menu.gui.button.biome",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    TIME_OF_DAY(
            "minecraft_access.access_menu.gui.button.time_of_day",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    XP_LEVEL(
            "minecraft_access.access_menu.gui.button.xp",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    REFRESH_SCREEN_READER(
            "minecraft_access.access_menu.gui.button.refresh_screen_reader",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    OPEN_CONFIG_MENU(
            "minecraft_access.access_menu.gui.button.open_config_menu",
            InputConstants.Type.KEYSYM,
            InputConstants.UNKNOWN.getValue(),
            "minecraft_access.keys.other.group_name"
    ),
    DIRECTION_NARRATION_KEY("minecraft_access.keys.other.facing_direction_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_H,
            "minecraft_access.keys.other.group_name"
    ),
    NARRATE_HELD_ITEM_KEY(
            "minecraft_access.keys.other.narrate_held_item_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_GRAVE,
            "minecraft_access.keys.other.group_name"
    ),

    CAMERA_CONTROLS_UP(
            "minecraft_access.keys.camera_controls.up_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_I,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_RIGHT(
            "minecraft_access.keys.camera_controls.right_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_L,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_DOWN(
            "minecraft_access.keys.camera_controls.down_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_K,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_LEFT(
            "minecraft_access.keys.camera_controls.left_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_J,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_ALTERNATE_UP(
            "minecraft_access.keys.camera_controls.alternate_up_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD8,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_ALTERNATE_RIGHT(
            "minecraft_access.keys.camera_controls.alternate_right_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD6,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_ALTERNATE_DOWN(
            "minecraft_access.keys.camera_controls.alternate_down_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD2,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_ALTERNATE_LEFT(
            "minecraft_access.keys.camera_controls.alternate_left_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD4,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_NORTH(
            "minecraft_access.keys.camera_controls.north_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD7,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_EAST(
            "minecraft_access.keys.camera_controls.east_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD9,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_WEST(
            "minecraft_access.keys.camera_controls.west_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD1,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_SOUTH(
            "minecraft_access.keys.camera_controls.south_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD3,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_CENTER_CAMERA(
            "minecraft_access.keys.camera_controls.center_camera_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD5,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_STRAIGHT_UP(
            "minecraft_access.keys.camera_controls.straight_up_camera_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPAD0,
            "minecraft_access.keys.camera_controls.group_name"
    ),
    CAMERA_CONTROLS_STRAIGHT_DOWN(
            "minecraft_access.keys.camera_controls.straight_down_camera_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_NUMPADCOMMA,
            "minecraft_access.keys.camera_controls.group_name"
    ),

    INVENTORY_CONTROLS_GROUP_KEY(
            "minecraft_access.keys.inventory_controls.change_group_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_C,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_UP_KEY(
            "minecraft_access.keys.inventory_controls.up_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_I,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_RIGHT_KEY(
            "minecraft_access.keys.inventory_controls.right_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_L,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_DOWN_KEY(
            "minecraft_access.keys.inventory_controls.down_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_K,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_LEFT_KEY(
            "minecraft_access.keys.inventory_controls.left_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_J,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_SWITCH_TAB_KEY(
            "minecraft_access.keys.inventory_controls.switch_tabs_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_V,
            "minecraft_access.keys.inventory_controls.group_name"
    ),
    INVENTORY_CONTROLS_TOGGLE_CRAFTABLE_KEY(
            "minecraft_access.keys.inventory_controls.toggle_craftable_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_R,
            "minecraft_access.keys.inventory_controls.group_name"
    ),

    MOUSE_SIMULATION_LEFT_MOUSE_KEY(
            "minecraft_access.keys.mouse_simulation.left_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_LBRACKET,
            "minecraft_access.keys.mouse_simulation.group_name"
    ),
    MOUSE_SIMULATION_RIGHT_MOUSE_KEY(
            "minecraft_access.keys.mouse_simulation.right_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_RBRACKET,
            "minecraft_access.keys.mouse_simulation.group_name"
    ),
    MOUSE_SIMULATION_MIDDLE_MOUSE_KEY(
            "minecraft_access.keys.mouse_simulation.middle_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_BACKSLASH,
            "minecraft_access.keys.mouse_simulation.group_name"
    ),
    MOUSE_SIMULATION_SCROLL_UP_KEY(
            "minecraft_access.keys.mouse_simulation.scroll_up_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_SEMICOLON,
            "minecraft_access.keys.mouse_simulation.group_name"
    ),
    MOUSE_SIMULATION_SCROLL_DOWN_KEY(
            "minecraft_access.keys.mouse_simulation.scroll_down_key_name",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_APOSTROPHE,
            "minecraft_access.keys.mouse_simulation.group_name"
    ),

    OBJECT_TRACKER_NEXT_ITEM(
            "minecraft_access.keys.object_tracker.next_item",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_PAGEDOWN,
            "minecraft_access.keys.object_tracker.group_name"
    ),
    OBJECT_TRACKER_PREVIOUS_ITEM(
            "minecraft_access.keys.object_tracker.previous_item",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_PAGEUP,
            "minecraft_access.keys.object_tracker.group_name"
    ),
    OBJECT_TRACKER_NARRATE_CURRENT_OBJECT(
            "minecraft_access.keys.object_tracker.narrate_current_object",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_HOME,
            "minecraft_access.keys.object_tracker.group_name"
    ),
    TARGET_NEAREST_OBJECT(
            "minecraft_access.keys.object_tracker.target_nearest",
            InputConstants.Type.KEYSYM,
            InputConstants.KEY_END,
            "minecraft_access.keys.object_tracker.group_name"
    );

    public final KeyMapping mapping;

    KeyBindingsHandler(String name, InputConstants.Type type, int keyCode, String category) {
        mapping = new KeyMapping(name, type, keyCode, category);
    }
}
