package org.mcaccess.minecraftaccess.utils;

import com.mojang.blaze3d.platform.InputConstants;
import net.minecraft.client.KeyMapping;
import net.minecraft.resources.ResourceLocation;

import org.mcaccess.minecraftaccess.MainClass;

/**
 * Initializes all the keybindings used by the mod.
 */
public final class KeyBindingsHandler {
    private KeyBindingsHandler() {
    }

    private enum Categories {
        OTHER("other"),
        CAMERA_CONTROLS("camera_controls"),
        INVENTORY_CONTROLS("inventory_controls"),
        MOUSE_SIMULATION("mouse_simulation"),
        OBJECT_TRACKER("object_tracker");

        public final KeyMapping.Category category;

        Categories(String name) {
            category = KeyMapping.Category.register(ResourceLocation.fromNamespaceAndPath(MainClass.MOD_ID, name));
        }
    }

    public enum Keys {
        NARRATE_PLAYER_STATUS_KEY(
                "minecraft_access.keys.other.player_status_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_R,
                Categories.OTHER
        ),
        NARRATE_BOSSBARS_KEY(
                "minecraft_access.keys.other.narrate_bossbars_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_U,
                Categories.OTHER
        ),
        LOCKING_HANDLER_KEY(
                "minecraft_access.keys.other.locking_handler_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_Y,
                Categories.OTHER
        ),
        POSITION_NARRATION_KEY(
                "minecraft_access.keys.other.player_position_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_V,
                Categories.OTHER
        ),
        ACCESS_MENU_KEY(
                "minecraft_access.keys.other.access_menu_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_F4,
                Categories.OTHER
        ),
        NARRATE_TARGET(
                "minecraft_access.access_menu.gui.button.block_and_fluid_target_info",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_B,
                Categories.OTHER
        ),
        TARGET_POSITION(
                "minecraft_access.access_menu.gui.button.block_and_fluid_target_position",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        LIGHT_LEVEL(
                "minecraft_access.access_menu.gui.button.light_level",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        CLOSEST_WATER_SOURCE(
                "minecraft_access.access_menu.gui.button.find_water",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        CLOSEST_LAVA_SOURCE(
                "minecraft_access.access_menu.gui.button.find_lava",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        CURRENT_BIOME(
                "minecraft_access.access_menu.gui.button.biome",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        TIME_OF_DAY(
                "minecraft_access.access_menu.gui.button.time_of_day",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        XP_LEVEL(
                "minecraft_access.access_menu.gui.button.xp",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        REFRESH_SCREEN_READER(
                "minecraft_access.access_menu.gui.button.refresh_screen_reader",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        OPEN_CONFIG_MENU(
                "minecraft_access.access_menu.gui.button.open_config_menu",
                InputConstants.Type.KEYSYM,
                InputConstants.UNKNOWN.getValue(),
                Categories.OTHER
        ),
        DIRECTION_NARRATION_KEY("minecraft_access.keys.other.facing_direction_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_H,
                Categories.OTHER
        ),
        NARRATE_HELD_ITEM_KEY(
                "minecraft_access.keys.other.narrate_held_item_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_GRAVE,
                Categories.OTHER
        ),

        CAMERA_CONTROLS_UP(
                "minecraft_access.keys.camera_controls.up_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_I,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_RIGHT(
                "minecraft_access.keys.camera_controls.right_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_L,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_DOWN(
                "minecraft_access.keys.camera_controls.down_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_K,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_LEFT(
                "minecraft_access.keys.camera_controls.left_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_J,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_ALTERNATE_UP(
                "minecraft_access.keys.camera_controls.alternate_up_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD8,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_ALTERNATE_RIGHT(
                "minecraft_access.keys.camera_controls.alternate_right_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD6,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_ALTERNATE_DOWN(
                "minecraft_access.keys.camera_controls.alternate_down_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD2,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_ALTERNATE_LEFT(
                "minecraft_access.keys.camera_controls.alternate_left_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD4,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_NORTH(
                "minecraft_access.keys.camera_controls.north_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD7,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_EAST(
                "minecraft_access.keys.camera_controls.east_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD9,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_WEST(
                "minecraft_access.keys.camera_controls.west_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD1,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_SOUTH(
                "minecraft_access.keys.camera_controls.south_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD3,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_CENTER_CAMERA(
                "minecraft_access.keys.camera_controls.center_camera_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD5,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_STRAIGHT_UP(
                "minecraft_access.keys.camera_controls.straight_up_camera_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPAD0,
                Categories.CAMERA_CONTROLS
        ),
        CAMERA_CONTROLS_STRAIGHT_DOWN(
                "minecraft_access.keys.camera_controls.straight_down_camera_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_NUMPADCOMMA,
                Categories.CAMERA_CONTROLS
        ),

        INVENTORY_CONTROLS_GROUP_KEY(
                "minecraft_access.keys.inventory_controls.change_group_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_C,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_UP_KEY(
                "minecraft_access.keys.inventory_controls.up_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_I,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_RIGHT_KEY(
                "minecraft_access.keys.inventory_controls.right_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_L,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_DOWN_KEY(
                "minecraft_access.keys.inventory_controls.down_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_K,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_LEFT_KEY(
                "minecraft_access.keys.inventory_controls.left_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_J,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_SWITCH_TAB_KEY(
                "minecraft_access.keys.inventory_controls.switch_tabs_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_V,
                Categories.INVENTORY_CONTROLS
        ),
        INVENTORY_CONTROLS_TOGGLE_CRAFTABLE_KEY(
                "minecraft_access.keys.inventory_controls.toggle_craftable_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_R,
                Categories.INVENTORY_CONTROLS
        ),

        MOUSE_SIMULATION_LEFT_MOUSE_KEY(
                "minecraft_access.keys.mouse_simulation.left_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_LBRACKET,
                Categories.MOUSE_SIMULATION
        ),
        MOUSE_SIMULATION_RIGHT_MOUSE_KEY(
                "minecraft_access.keys.mouse_simulation.right_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_RBRACKET,
                Categories.MOUSE_SIMULATION
        ),
        MOUSE_SIMULATION_MIDDLE_MOUSE_KEY(
                "minecraft_access.keys.mouse_simulation.middle_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_BACKSLASH,
                Categories.MOUSE_SIMULATION
        ),
        MOUSE_SIMULATION_SCROLL_UP_KEY(
                "minecraft_access.keys.mouse_simulation.scroll_up_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_SEMICOLON,
                Categories.MOUSE_SIMULATION
        ),
        MOUSE_SIMULATION_SCROLL_DOWN_KEY(
                "minecraft_access.keys.mouse_simulation.scroll_down_key_name",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_APOSTROPHE,
                Categories.MOUSE_SIMULATION
        ),

        OBJECT_TRACKER_NEXT_ITEM(
                "minecraft_access.keys.object_tracker.next_item",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_PAGEDOWN,
                Categories.OBJECT_TRACKER
        ),
        OBJECT_TRACKER_PREVIOUS_ITEM(
                "minecraft_access.keys.object_tracker.previous_item",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_PAGEUP,
                Categories.OBJECT_TRACKER
        ),
        OBJECT_TRACKER_NARRATE_CURRENT_OBJECT(
                "minecraft_access.keys.object_tracker.narrate_current_object",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_HOME,
                Categories.OBJECT_TRACKER
        ),
        TARGET_NEAREST_OBJECT(
                "minecraft_access.keys.object_tracker.target_nearest",
                InputConstants.Type.KEYSYM,
                InputConstants.KEY_END,
                Categories.OBJECT_TRACKER
        );

        public final KeyMapping mapping;

        Keys(String name, InputConstants.Type type, int keyCode, Categories category) {
            mapping = new KeyMapping(name, type, keyCode, category.category);
        }
    }
}
