architectury {
    common("fabric", "neoforge")
}

idea {
    module {
        excludeDirs += file('./logs/')
    }
}

dependencies {
    modImplementation libs.jadeFabric
    modImplementation libs.balm
    modImplementation libs.clothConfig

    // https://projectlombok.org/setup/gradle
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    // Unit test dependencies
    testImplementation libs.junitJupiter
    testImplementation libs.junitJupiterParams
    testRuntimeOnly libs.junitPlatformLauncher
    testImplementation libs.assertjCore
    testImplementation libs.mockitoCore
    testImplementation libs.mockitoJunitJupiter

    // benchmark dependencies
    testImplementation libs.jmhCore
    testAnnotationProcessor libs.jmhGeneratorAnnprocess
}

test {
    useJUnitPlatform()
    // Suppress JVM warning about mockito's behavior when running unit tests with IntelliJ
    // ref: https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}
