modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/minecraft-access/minecraft-access/issues"
license = "GNU GPLv3"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib, Boholder, TheSuperGamer20578, BrailleBennett, Molitvan"
description = '''
A mod that helps visually impaired players to play Minecraft.
'''
logoFile = "logo-mc-access.png"
modUrl = "https://modrinth.com/mod/minecraft-access"
displayURL = "https://mcaccess.org"

[[dependencies.minecraft_access]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"

[[dependencies.minecraft_access]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"

[[dependencies.minecraft_access]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "BEFORE"
side = "CLIENT"

[[dependencies.minecraft_access]]
modId = "jade"
type = "optional"
reason = "Jade can be used to integrate with the built in narrator of the mod by improving support with other mods and providing more information about things you look at"
versionRange = "[${jade_neoforge_version},)"

[[dependencies.minecraft_access]]
modId = "cloth_config"
type = "required"

[[mixins]]
config = "minecraft_access.mixins.json"

[[mixins]]
config = "minecraft_access-compat.mixins.json"
