modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/minecraft-access/minecraft-access/issues"
license = "GNU GPLv3"

[[mods]]
modId = "minecraft_access"
version = "${version}"
displayName = "Minecraft Access"
authors = "Shoaib, Boholder, TheSuperGamer20578"
description = '''
A mod that helps visually impaired players to play Minecraft.
'''
logoFile = "logo-mc-access.png"

[[dependencies.minecraft_access]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minecraft_access]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "minecraft_access.mixins.json"
