name: Publish PR Build
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: temurin

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        # language=bash
        run: |
          ./gradlew clean build -x test
          shopt -s extglob
          cp ./!(common)/build/libs/*+!(*-*).jar .
      - uses: actions/upload-artifact@v4
        with:
          name: "minecraft-access"
          path: "./*.jar"
      - uses: actions/attest-build-provenance@v1
        if: github.event_name != 'pull_request'
        with:
          subject-path: "./*.jar"
