name: Build
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      central:
        type: boolean
        required: false
        default: false
    secrets:
      centralUsername:
        required: false
      centralPassword:
        required: false
      gpgKey:
        required: false

env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: temurin
  PULL_REQUEST: ${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.number || null }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.centralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.centralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.gpgKey }}
        # language=bash
        run: |
          ./gradlew clean build ${{ inputs.central && 'publishAndReleaseToMavenCentral' || '' }} -x check
          cp $(ls -1 ./build/libs/minecraft-access-*.jar | awk '{ print length, $0 }' | sort -n | cut -d" " -f2- | head -n 1) .
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: "minecraft-access"
          path: "./*.jar"
      - uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8
        if: github.event_name != 'pull_request'
        with:
          subject-path: "./*.jar"
