name: Build
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      central:
        type: boolean
        required: false
        default: false
    secrets:
      centralUsername:
        required: false
      centralPassword:
        required: false
      gpgKey:
        required: false

env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: temurin
  PULL_REQUEST: ${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.number || null }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.centralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.centralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.gpgKey }}
        # language=bash
        run: |
          ./gradlew clean build ${{ inputs.central && 'publishAndReleaseToMavenCentral' || '' }} -x check
          cp $(ls -1 ./build/libs/minecraft-access-*.jar | awk '{ print length, $0 }' | sort -n | cut -d" " -f2- | head -n 1) .
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: "minecraft-access"
          path: "./*.jar"
      - uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373
        if: github.event_name != 'pull_request'
        with:
          subject-path: "./*.jar"
