name: Push
on:
  push:
  pull_request:

env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: temurin

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Test
        # language=bash
        run: ./gradlew clean test
